### ISSUE TITLE
redundant and harmful (?) extra claimInformer.Run

### ISSUE THREAD

**Issue by pohly** [kubernetes-csi/external-provisioner#595]
As pointed out in https://github.com/kubernetes-csi/external-provisioner/pull/590, informers should only be started once. That PR fixes that for the capacity controller. The cloning protection controller still has a `claimInformer.Run()` that probably should be removed:
https://github.com/kubernetes-csi/external-provisioner/blob/bcf1a405b5f6a0fa2aadb80d08c9c2569c4b6912/pkg/controller/clone_controller.go#L82

It is not clear whether that has negative consequences.

**Comment by msau42** [comment]
My rough understanding of the issue was that multiple events may be called on the same object, which caused the capacity controller to create multiple objects. To me, that sounds like a synchronization or idempotency controller issue.

**Comment by pohly** [comment]
The bug was that `Run` was called more than once. What negative effect that has depends on the callbacks registered with the informer, but it is wrong regardless of that. Even if the callbacks happen to be idempotent, calling `Run` causes extra resource consumption or worse - it's not allowed, so who knows what else can break.

**Comment by msau42** [comment]
But the fact that multiple capacity objects were created seems to indicate to me there's an issue in that the names are not deterministic so it can't detect duplicate objects.

**Comment by pohly** [comment]
> But the fact that multiple capacity objects were created seems to indicate to me there's an issue in that the names are not deterministic so it can't detect duplicate objects.

Object names are generated and random, so extra code would be needed to avoid duplicates. An informer promises that it only reports new objects once. Are you saying that code shouldn't trust that promise and have defensive code paths to detect situations where the informer misbehaves and reports the same object twice as new?

**Comment by msau42** [comment]
I don't think we necessarily have to have defensive code for a specific dependency, however I'm just thinking of ways that we can design the logic to be more defensive and idempotent against this general class of problem.

**Comment by pohly** [comment]
/remove-lifecycle stale

I still think the extra `Run` invocation is a bug.

**Comment by tksm** [comment]
Hello,

I think that calling `informer.Run()` twice may cause a panic. It might be the cause of the following issues.

- https://github.com/kubernetes-csi/external-provisioner/issues/582
- https://github.com/rook/rook/issues/8128

You can reproduce the panic with the following test code.

```go
package main

import (
	"fmt"
	"testing"
	"time"

	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	"k8s.io/client-go/tools/cache"
	fcache "k8s.io/client-go/tools/cache/testing"
)

func TestInformerRunTwice(t *testing.T) {
	source := fcache.NewFakeControllerSource()
	for i := 0; i < 1000000; i++ {
		source.Add(&v1.Pod{ObjectMeta: metav1.ObjectMeta{Name: fmt.Sprintf("pod-%d", i)}})
	}

	informer := cache.NewSharedInformer(source, &v1.Pod{}, 1*time.Second)
	handler := cache.ResourceEventHandlerFuncs{
		// do nothing
	}
	informer.AddEventHandler(handler)

	stop := make(chan struct{})
	defer close(stop)

	// Call informer.Run() twice
	go informer.Run(stop)
	go informer.Run(stop)

	time.Sleep(30 * time.Second)
}
```

You will get a panic after multiple `unrecognized notification: <nil>` errors.  If you remove one `informer.Run()`, there will be no panic.

```
$ go test -v . -run InformerRunTwice
=== RUN   TestInformerRunTwice
E0714 16:40:13.052316   48554 shared_informer.go:781] unrecognized notification: <nil>
E0714 16:40:13.108535   48554 shared_informer.go:781] unrecognized notification: <nil>
...
E0714 16:40:14.044241   48554 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 66 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17f4100, 0x1dd8cc0)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/runtime/runtime.go:48 +0x86
panic(0x17f4100, 0x1dd8cc0)
        /usr/local/Cellar/go/1.16.5/libexec/src/runtime/panic.go:965 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
        /Users/tkusumi/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:776 +0xa3
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0005cb760)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc050e88f60, 0x19a3840, 0xc0001fe240, 0x17e2601, 0xc050e8a000)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0005cb760, 0x3b9aca00, 0x0, 0x1, 0xc050e8a000)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/cache.(*processorListener).run(0xc000046080)
        /Users/tkusumi/pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/shared_informer.go:771 +0x95
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00024a0d0, 0xc011314000)
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:73 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /Users/tkusumi/pkg/mod/k8s.io/apimachinery@v0.21.2/pkg/util/wait/wait.go:71 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x176b583]
...
```

**Comment by tksm** [comment]
I also confirmed the data race on CloneProtector by [Go Race Detector](https://blog.golang.org/race-detector). I added the following test code to [clone_controller_test.go](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/clone_controller_test.go).

```go
func TestCloneProtectorRace(t *testing.T) {
	objects := []runtime.Object{}
	clientSet := fakeclientset.NewSimpleClientset(objects...)
	cloningProtector := fakeCloningProtector(clientSet, objects...)
	ctx := context.Background()
	cloningProtector.Run(ctx, 1)
}
```

With `-race` option, the data race was detected on `(*CloningProtectionController).Run()`

```
go test -v -race -run CloneProtectorRace github.com/kubernetes-csi/external-provisioner/pkg/controller
```

<details>
<summary>output</summary>

```
=== RUN   TestCloneProtectorRace
I0715 14:51:40.129751   87904 clone_controller.go:66] Starting CloningProtection controller
I0715 14:51:40.131653   87904 clone_controller.go:84] Started CloningProtection controller
==================
WARNING: DATA RACE
Write at 0x00c0003b5f50 by goroutine 39:
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:392 +0x1d8
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:395 +0x4d6
Write at 0x00c0003b5f50 by goroutine 39:
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:392 +0x1d8
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:395 +0x4d6

Previous read at 0x00c0003b5f50 by goroutine 33:
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:410 +0x79d

Goroutine 39 (running) created at:
  github.com/kubernetes-csi/external-provisioner/pkg/controller.(*CloningProtectionController).Run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/pkg/controller/clone_controller.go:82 +0x5c4
  github.com/kubernetes-csi/external-provisioner/pkg/controller.TestCloneProtectorRace()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/pkg/controller/clone_controller_test.go:214 +0xb3
  testing.tRunner()
      /usr/local/Cellar/go/1.16.5/libexec/src/testing/testing.go:1193 +0x202

Goroutine 33 (running) created at:
  k8s.io/client-go/informers.(*sharedInformerFactory).Start()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/informers/factory.go:134 +0x252
==================
==================
WARNING: DATA RACE
Write at 0x00c000276fc0 by goroutine 35:
  k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:626 +0x27a
  k8s.io/client-go/tools/cache.(*sharedProcessor).run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:627 +0x55
  k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:618 +0x54
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x45
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x6d

Previous write at 0x00c000276fc0 by goroutine 42:
  k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:626 +0x27a
  k8s.io/client-go/tools/cache.(*sharedProcessor).run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:627 +0x55
  k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:618 +0x54
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x45
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x6d


Previous write at 0x00c000276fc0 by goroutine 42:
  k8s.io/client-go/tools/cache.(*sharedProcessor).run.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:626 +0x27a
  k8s.io/client-go/tools/cache.(*sharedProcessor).run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:627 +0x55
  k8s.io/client-go/tools/cache.(*sharedProcessor).run-fm()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:618 +0x54
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:56 +0x45
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:73 +0x6d

Goroutine 35 (running) created at:
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x70
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:55 +0xc5
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:403 +0x752

Goroutine 42 (running) created at:
  k8s.io/apimachinery/pkg/util/wait.(*Group).Start()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x70
  k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:55 +0xc5
  k8s.io/client-go/tools/cache.(*sharedIndexInformer).Run()
      /Users/tkusumi/src/github.com/kubernetes-csi/external-provisioner/vendor/k8s.io/client-go/tools/cache/shared_informer.go:403 +0x752
==================
```

</details>
